### ISSUE TITLE
Markdownをエスケープしていない

### ISSUE THREAD

**Issue by NanasuNANA** [kiridaruma/BCDiceCord#7]
Markdownをエスケープしていないため、たとえば掛け算をすると

(2D6\*2) ＞ 7[2,5]\*2 ＞ 14

の\*がMarkdown記法と見なされて斜体になります。

**Comment by kiridaruma** [comment]
すいません、今確認しました
Issue投げてもらったのに、反応できずホントすいません...
来週中には対応しておきますー
